install.packages("magrittr")
install.packages("lumberjack")
install.packages("stringr")
install.packages("dplyr")
install.packages("data.table")
install.packages("remotes")
library(remotes)
remotes::install_github("bnosac/word2vec")
